name: com.floridainc.dosparkles
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  fish_redux: ^0.3.7
  common_utils: ^1.2.1
  shared_preferences: ^0.5.3+4
  permission_handler: ^5.0.1+1

  # firebase
  firebase_core:
  firebase_messaging:
  firebase_analytics:
  # firebase_crashlytics:

  flutter_local_notifications: ^3.0.0
  graphql_flutter:
  toast: ^0.1.5
  dio: ^3.0.9
  dio_http_cache: ^0.2.5
  flutter_downloader: ^1.3.4
  provider: ^4.0.5
  lottie: ^0.7.0+1
  font_awesome_flutter: ^8.5.0
  cached_network_image: ^2.0.0
  package_info: ^0.4.0+16
  dart_strapi: ^0.0.3
  table_calendar: ^2.3.0
  flutter_swiper: ^1.1.6
  flui: ^0.9.2
  url_launcher:
  list_tile_more_customizable: ^1.3.3
  map_launcher: ^1.0.0
  multi_image_picker: ^4.7.15
  http:
  http_parser: ^3.1.4
  flutter_facebook_login: ^3.0.0
  share: ^0.6.5+4
  geolocator: ^6.2.1
  contacts_service: ^0.4.6
  google_sign_in:
  stripe_payment: ^1.1.0
  sign_in_with_apple: ^2.5.4
  flutter_branch_sdk: ^1.4.0
  country_pickers: ^2.0.0
  bubble: ^1.2.1
  flutter_svg:
  cupertino_icons: ^1.0.0
  flutter_dash: ^0.0.1
  email_validator: ^2.0.1
  connectivity:
  social_share: ^2.0.5
  flutter_credit_card: ^0.1.4
  mask_text_input_formatter: ^1.2.1
  flutter_widget_from_html: ^0.5.0
  custom_refresh_indicator: ^0.9.0
  liquid_pull_to_refresh: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  better_player:
  uuid:
  video_player:
    git:
      url: https://github.com/sanekyy/plugins.git
      ref: caching
      path: packages/video_player/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  video_player:
    git:
      url: https://github.com/sanekyy/plugins.git
      ref: caching
      path: packages/video_player/video_player
  sqflite:
    git:
      url: https://github.com/TinyProgrammers/sqflite.git
      path: sqflite

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/high-quality-images/
    - appconfig.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# keytool -keystore C:\Users\User\Key\key.jks -list -v
# E3:78:B7:94:A1:C1:BD:BA:C3:7B:D0:2F:04:A9:B5:E7:22:09:42:6E:CF:69:13:95:0B:41:CD:FA:42:4B:B8:3E

